name: GlobalShopN
main: com.bc.gsn
version: "0.2.31"
author: bcN
api: ["1.0.0"]
description: "全球经济插件 GlobalShopN"
depend:
  - EconomyAPI
commands:
  gsn:
    aliases: []
    description: From GlobalShopN
    usage: "/gsn help"
permissions:
  gsn.use:
    default: true
  gsn.admin:
    default: op
  gsn.adminMail:
    default: op